# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.79.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime

from pydantic import BaseModel, Field, StrictStr

class AdminSignupResponseDto(BaseModel):
    """
    AdminSignupResponseDto
    """
    created_at: datetime = Field(..., alias="createdAt")
    email: StrictStr = Field(...)
    first_name: StrictStr = Field(..., alias="firstName")
    id: StrictStr = Field(...)
    last_name: StrictStr = Field(..., alias="lastName")
    __properties = ["createdAt", "email", "firstName", "id", "lastName"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> AdminSignupResponseDto:
        """Create an instance of AdminSignupResponseDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> AdminSignupResponseDto:
        """Create an instance of AdminSignupResponseDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return AdminSignupResponseDto.parse_obj(obj)

        _obj = AdminSignupResponseDto.parse_obj({
            "created_at": obj.get("createdAt"),
            "email": obj.get("email"),
            "first_name": obj.get("firstName"),
            "id": obj.get("id"),
            "last_name": obj.get("lastName")
        })
        return _obj


