# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.79.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List
from pydantic import BaseModel, Field, conlist
from openapi_client.models.asset_bulk_upload_check_item import AssetBulkUploadCheckItem

class AssetBulkUploadCheckDto(BaseModel):
    """
    AssetBulkUploadCheckDto
    """
    assets: conlist(AssetBulkUploadCheckItem) = Field(...)
    __properties = ["assets"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> AssetBulkUploadCheckDto:
        """Create an instance of AssetBulkUploadCheckDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in assets (list)
        _items = []
        if self.assets:
            for _item in self.assets:
                if _item:
                    _items.append(_item.to_dict())
            _dict['assets'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> AssetBulkUploadCheckDto:
        """Create an instance of AssetBulkUploadCheckDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return AssetBulkUploadCheckDto.parse_obj(obj)

        _obj = AssetBulkUploadCheckDto.parse_obj({
            "assets": [AssetBulkUploadCheckItem.from_dict(_item) for _item in obj.get("assets")] if obj.get("assets") is not None else None
        })
        return _obj


