# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.79.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictStr

class ServerConfigDto(BaseModel):
    """
    ServerConfigDto
    """
    login_page_message: StrictStr = Field(..., alias="loginPageMessage")
    map_tile_url: StrictStr = Field(..., alias="mapTileUrl")
    oauth_button_text: StrictStr = Field(..., alias="oauthButtonText")
    __properties = ["loginPageMessage", "mapTileUrl", "oauthButtonText"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ServerConfigDto:
        """Create an instance of ServerConfigDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ServerConfigDto:
        """Create an instance of ServerConfigDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ServerConfigDto.parse_obj(obj)

        _obj = ServerConfigDto.parse_obj({
            "login_page_message": obj.get("loginPageMessage"),
            "map_tile_url": obj.get("mapTileUrl"),
            "oauth_button_text": obj.get("oauthButtonText")
        })
        return _obj


