# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.79.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictInt
from openapi_client.models.colorspace import Colorspace

class SystemConfigThumbnailDto(BaseModel):
    """
    SystemConfigThumbnailDto
    """
    colorspace: Colorspace = Field(...)
    jpeg_size: StrictInt = Field(..., alias="jpegSize")
    quality: StrictInt = Field(...)
    webp_size: StrictInt = Field(..., alias="webpSize")
    __properties = ["colorspace", "jpegSize", "quality", "webpSize"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> SystemConfigThumbnailDto:
        """Create an instance of SystemConfigThumbnailDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> SystemConfigThumbnailDto:
        """Create an instance of SystemConfigThumbnailDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return SystemConfigThumbnailDto.parse_obj(obj)

        _obj = SystemConfigThumbnailDto.parse_obj({
            "colorspace": obj.get("colorspace"),
            "jpeg_size": obj.get("jpegSize"),
            "quality": obj.get("quality"),
            "webp_size": obj.get("webpSize")
        })
        return _obj


