# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.79.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictInt, StrictStr

class UsageByUserDto(BaseModel):
    """
    UsageByUserDto
    """
    photos: StrictInt = Field(...)
    usage: StrictInt = Field(...)
    user_first_name: StrictStr = Field(..., alias="userFirstName")
    user_id: StrictStr = Field(..., alias="userId")
    user_last_name: StrictStr = Field(..., alias="userLastName")
    videos: StrictInt = Field(...)
    __properties = ["photos", "usage", "userFirstName", "userId", "userLastName", "videos"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> UsageByUserDto:
        """Create an instance of UsageByUserDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> UsageByUserDto:
        """Create an instance of UsageByUserDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return UsageByUserDto.parse_obj(obj)

        _obj = UsageByUserDto.parse_obj({
            "photos": obj.get("photos"),
            "usage": obj.get("usage"),
            "user_first_name": obj.get("userFirstName"),
            "user_id": obj.get("userId"),
            "user_last_name": obj.get("userLastName"),
            "videos": obj.get("videos")
        })
        return _obj


