# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.79.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictStr
from openapi_client.models.api_key_response_dto import APIKeyResponseDto

class APIKeyCreateResponseDto(BaseModel):
    """
    APIKeyCreateResponseDto
    """
    api_key: APIKeyResponseDto = Field(..., alias="apiKey")
    secret: StrictStr = Field(...)
    __properties = ["apiKey", "secret"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> APIKeyCreateResponseDto:
        """Create an instance of APIKeyCreateResponseDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of api_key
        if self.api_key:
            _dict['apiKey'] = self.api_key.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> APIKeyCreateResponseDto:
        """Create an instance of APIKeyCreateResponseDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return APIKeyCreateResponseDto.parse_obj(obj)

        _obj = APIKeyCreateResponseDto.parse_obj({
            "api_key": APIKeyResponseDto.from_dict(obj.get("apiKey")) if obj.get("apiKey") is not None else None,
            "secret": obj.get("secret")
        })
        return _obj


