# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.79.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class AudioCodec(str, Enum):
    """
    AudioCodec
    """

    """
    allowed enum values
    """
    MP3 = 'mp3'
    AAC = 'aac'
    LIBOPUS = 'libopus'

    @classmethod
    def from_json(cls, json_str: str) -> AudioCodec:
        """Create an instance of AudioCodec from a JSON string"""
        return AudioCodec(json.loads(json_str))


