# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.79.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictBool, StrictInt, StrictStr
from openapi_client.models.model_type import ModelType

class ClassificationConfig(BaseModel):
    """
    ClassificationConfig
    """
    enabled: StrictBool = Field(...)
    min_score: StrictInt = Field(..., alias="minScore")
    model_name: StrictStr = Field(..., alias="modelName")
    model_type: Optional[ModelType] = Field(None, alias="modelType")
    __properties = ["enabled", "minScore", "modelName", "modelType"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ClassificationConfig:
        """Create an instance of ClassificationConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ClassificationConfig:
        """Create an instance of ClassificationConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ClassificationConfig.parse_obj(obj)

        _obj = ClassificationConfig.parse_obj({
            "enabled": obj.get("enabled"),
            "min_score": obj.get("minScore"),
            "model_name": obj.get("modelName"),
            "model_type": obj.get("modelType")
        })
        return _obj


