# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.79.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class CQMode(str, Enum):
    """
    CQMode
    """

    """
    allowed enum values
    """
    AUTO = 'auto'
    CQP = 'cqp'
    ICQ = 'icq'

    @classmethod
    def from_json(cls, json_str: str) -> CQMode:
        """Create an instance of CQMode from a JSON string"""
        return CQMode(json.loads(json_str))


