# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.79.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictBool, StrictStr

class CreateUserDto(BaseModel):
    """
    CreateUserDto
    """
    email: StrictStr = Field(...)
    external_path: Optional[StrictStr] = Field(None, alias="externalPath")
    first_name: StrictStr = Field(..., alias="firstName")
    last_name: StrictStr = Field(..., alias="lastName")
    memories_enabled: Optional[StrictBool] = Field(None, alias="memoriesEnabled")
    password: StrictStr = Field(...)
    storage_label: Optional[StrictStr] = Field(None, alias="storageLabel")
    __properties = ["email", "externalPath", "firstName", "lastName", "memoriesEnabled", "password", "storageLabel"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CreateUserDto:
        """Create an instance of CreateUserDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if external_path (nullable) is None
        # and __fields_set__ contains the field
        if self.external_path is None and "external_path" in self.__fields_set__:
            _dict['externalPath'] = None

        # set to None if storage_label (nullable) is None
        # and __fields_set__ contains the field
        if self.storage_label is None and "storage_label" in self.__fields_set__:
            _dict['storageLabel'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CreateUserDto:
        """Create an instance of CreateUserDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CreateUserDto.parse_obj(obj)

        _obj = CreateUserDto.parse_obj({
            "email": obj.get("email"),
            "external_path": obj.get("externalPath"),
            "first_name": obj.get("firstName"),
            "last_name": obj.get("lastName"),
            "memories_enabled": obj.get("memoriesEnabled"),
            "password": obj.get("password"),
            "storage_label": obj.get("storageLabel")
        })
        return _obj


