# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.79.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class LibraryType(str, Enum):
    """
    LibraryType
    """

    """
    allowed enum values
    """
    UPLOAD = 'UPLOAD'
    EXTERNAL = 'EXTERNAL'

    @classmethod
    def from_json(cls, json_str: str) -> LibraryType:
        """Create an instance of LibraryType from a JSON string"""
        return LibraryType(json.loads(json_str))


