# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.79.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, Field, StrictBool, StrictStr, conlist
from openapi_client.models.album_response_dto import AlbumResponseDto
from openapi_client.models.asset_response_dto import AssetResponseDto
from openapi_client.models.shared_link_type import SharedLinkType

class SharedLinkResponseDto(BaseModel):
    """
    SharedLinkResponseDto
    """
    album: Optional[AlbumResponseDto] = None
    allow_download: StrictBool = Field(..., alias="allowDownload")
    allow_upload: StrictBool = Field(..., alias="allowUpload")
    assets: conlist(AssetResponseDto) = Field(...)
    created_at: datetime = Field(..., alias="createdAt")
    description: Optional[StrictStr] = Field(...)
    expires_at: Optional[datetime] = Field(..., alias="expiresAt")
    id: StrictStr = Field(...)
    key: StrictStr = Field(...)
    show_exif: StrictBool = Field(..., alias="showExif")
    type: SharedLinkType = Field(...)
    user_id: StrictStr = Field(..., alias="userId")
    __properties = ["album", "allowDownload", "allowUpload", "assets", "createdAt", "description", "expiresAt", "id", "key", "showExif", "type", "userId"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> SharedLinkResponseDto:
        """Create an instance of SharedLinkResponseDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of album
        if self.album:
            _dict['album'] = self.album.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in assets (list)
        _items = []
        if self.assets:
            for _item in self.assets:
                if _item:
                    _items.append(_item.to_dict())
            _dict['assets'] = _items
        # set to None if description (nullable) is None
        # and __fields_set__ contains the field
        if self.description is None and "description" in self.__fields_set__:
            _dict['description'] = None

        # set to None if expires_at (nullable) is None
        # and __fields_set__ contains the field
        if self.expires_at is None and "expires_at" in self.__fields_set__:
            _dict['expiresAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> SharedLinkResponseDto:
        """Create an instance of SharedLinkResponseDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return SharedLinkResponseDto.parse_obj(obj)

        _obj = SharedLinkResponseDto.parse_obj({
            "album": AlbumResponseDto.from_dict(obj.get("album")) if obj.get("album") is not None else None,
            "allow_download": obj.get("allowDownload"),
            "allow_upload": obj.get("allowUpload"),
            "assets": [AssetResponseDto.from_dict(_item) for _item in obj.get("assets")] if obj.get("assets") is not None else None,
            "created_at": obj.get("createdAt"),
            "description": obj.get("description"),
            "expires_at": obj.get("expiresAt"),
            "id": obj.get("id"),
            "key": obj.get("key"),
            "show_exif": obj.get("showExif"),
            "type": obj.get("type"),
            "user_id": obj.get("userId")
        })
        return _obj


