# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.79.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictStr

class SignUpDto(BaseModel):
    """
    SignUpDto
    """
    email: StrictStr = Field(...)
    first_name: StrictStr = Field(..., alias="firstName")
    last_name: StrictStr = Field(..., alias="lastName")
    password: StrictStr = Field(...)
    __properties = ["email", "firstName", "lastName", "password"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> SignUpDto:
        """Create an instance of SignUpDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> SignUpDto:
        """Create an instance of SignUpDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return SignUpDto.parse_obj(obj)

        _obj = SignUpDto.parse_obj({
            "email": obj.get("email"),
            "first_name": obj.get("firstName"),
            "last_name": obj.get("lastName"),
            "password": obj.get("password")
        })
        return _obj


