# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.79.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictBool, StrictStr
from openapi_client.models.classification_config import ClassificationConfig
from openapi_client.models.clip_config import CLIPConfig
from openapi_client.models.recognition_config import RecognitionConfig

class SystemConfigMachineLearningDto(BaseModel):
    """
    SystemConfigMachineLearningDto
    """
    classification: ClassificationConfig = Field(...)
    clip: CLIPConfig = Field(...)
    enabled: StrictBool = Field(...)
    facial_recognition: RecognitionConfig = Field(..., alias="facialRecognition")
    url: StrictStr = Field(...)
    __properties = ["classification", "clip", "enabled", "facialRecognition", "url"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> SystemConfigMachineLearningDto:
        """Create an instance of SystemConfigMachineLearningDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of classification
        if self.classification:
            _dict['classification'] = self.classification.to_dict()
        # override the default output from pydantic by calling `to_dict()` of clip
        if self.clip:
            _dict['clip'] = self.clip.to_dict()
        # override the default output from pydantic by calling `to_dict()` of facial_recognition
        if self.facial_recognition:
            _dict['facialRecognition'] = self.facial_recognition.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> SystemConfigMachineLearningDto:
        """Create an instance of SystemConfigMachineLearningDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return SystemConfigMachineLearningDto.parse_obj(obj)

        _obj = SystemConfigMachineLearningDto.parse_obj({
            "classification": ClassificationConfig.from_dict(obj.get("classification")) if obj.get("classification") is not None else None,
            "clip": CLIPConfig.from_dict(obj.get("clip")) if obj.get("clip") is not None else None,
            "enabled": obj.get("enabled"),
            "facial_recognition": RecognitionConfig.from_dict(obj.get("facialRecognition")) if obj.get("facialRecognition") is not None else None,
            "url": obj.get("url")
        })
        return _obj


