# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.79.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr

class UpdateAlbumDto(BaseModel):
    """
    UpdateAlbumDto
    """
    album_name: Optional[StrictStr] = Field(None, alias="albumName")
    album_thumbnail_asset_id: Optional[StrictStr] = Field(None, alias="albumThumbnailAssetId")
    description: Optional[StrictStr] = None
    __properties = ["albumName", "albumThumbnailAssetId", "description"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> UpdateAlbumDto:
        """Create an instance of UpdateAlbumDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> UpdateAlbumDto:
        """Create an instance of UpdateAlbumDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return UpdateAlbumDto.parse_obj(obj)

        _obj = UpdateAlbumDto.parse_obj({
            "album_name": obj.get("albumName"),
            "album_thumbnail_asset_id": obj.get("albumThumbnailAssetId"),
            "description": obj.get("description")
        })
        return _obj


