# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.79.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictBool, StrictStr

class UpdateUserDto(BaseModel):
    """
    UpdateUserDto
    """
    email: Optional[StrictStr] = None
    external_path: Optional[StrictStr] = Field(None, alias="externalPath")
    first_name: Optional[StrictStr] = Field(None, alias="firstName")
    id: StrictStr = Field(...)
    is_admin: Optional[StrictBool] = Field(None, alias="isAdmin")
    last_name: Optional[StrictStr] = Field(None, alias="lastName")
    memories_enabled: Optional[StrictBool] = Field(None, alias="memoriesEnabled")
    password: Optional[StrictStr] = None
    should_change_password: Optional[StrictBool] = Field(None, alias="shouldChangePassword")
    storage_label: Optional[StrictStr] = Field(None, alias="storageLabel")
    __properties = ["email", "externalPath", "firstName", "id", "isAdmin", "lastName", "memoriesEnabled", "password", "shouldChangePassword", "storageLabel"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> UpdateUserDto:
        """Create an instance of UpdateUserDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> UpdateUserDto:
        """Create an instance of UpdateUserDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return UpdateUserDto.parse_obj(obj)

        _obj = UpdateUserDto.parse_obj({
            "email": obj.get("email"),
            "external_path": obj.get("externalPath"),
            "first_name": obj.get("firstName"),
            "id": obj.get("id"),
            "is_admin": obj.get("isAdmin"),
            "last_name": obj.get("lastName"),
            "memories_enabled": obj.get("memoriesEnabled"),
            "password": obj.get("password"),
            "should_change_password": obj.get("shouldChangePassword"),
            "storage_label": obj.get("storageLabel")
        })
        return _obj


