# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.79.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.system_config_api import SystemConfigApi  # noqa: E501


class TestSystemConfigApi(unittest.TestCase):
    """SystemConfigApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SystemConfigApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_get_config(self) -> None:
        """Test case for get_config

        """
        pass

    def test_get_defaults(self) -> None:
        """Test case for get_defaults

        """
        pass

    def test_get_storage_template_options(self) -> None:
        """Test case for get_storage_template_options

        """
        pass

    def test_update_config(self) -> None:
        """Test case for update_config

        """
        pass


if __name__ == '__main__':
    unittest.main()
