# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.79.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.sign_up_dto import SignUpDto  # noqa: E501

class TestSignUpDto(unittest.TestCase):
    """SignUpDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SignUpDto:
        """Test SignUpDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SignUpDto`
        """
        model = SignUpDto()  # noqa: E501
        if include_optional:
            return SignUpDto(
                email = 'testuser@email.com',
                first_name = 'Admin',
                last_name = 'Doe',
                password = 'password'
            )
        else:
            return SignUpDto(
                email = 'testuser@email.com',
                first_name = 'Admin',
                last_name = 'Doe',
                password = 'password',
        )
        """

    def testSignUpDto(self):
        """Test SignUpDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
