# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.79.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.change_password_dto import ChangePasswordDto  # noqa: E501

class TestChangePasswordDto(unittest.TestCase):
    """ChangePasswordDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChangePasswordDto:
        """Test ChangePasswordDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChangePasswordDto`
        """
        model = ChangePasswordDto()  # noqa: E501
        if include_optional:
            return ChangePasswordDto(
                new_password = 'password',
                password = 'password'
            )
        else:
            return ChangePasswordDto(
                new_password = 'password',
                password = 'password',
        )
        """

    def testChangePasswordDto(self):
        """Test ChangePasswordDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
