# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.79.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.server_stats_response_dto import ServerStatsResponseDto  # noqa: E501

class TestServerStatsResponseDto(unittest.TestCase):
    """ServerStatsResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServerStatsResponseDto:
        """Test ServerStatsResponseDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServerStatsResponseDto`
        """
        model = ServerStatsResponseDto()  # noqa: E501
        if include_optional:
            return ServerStatsResponseDto(
                photos = 56,
                usage = 56,
                usage_by_user = [{"photos":1,"videos":1,"diskUsageRaw":1}],
                videos = 56
            )
        else:
            return ServerStatsResponseDto(
                photos = 56,
                usage = 56,
                usage_by_user = [{"photos":1,"videos":1,"diskUsageRaw":1}],
                videos = 56,
        )
        """

    def testServerStatsResponseDto(self):
        """Test ServerStatsResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
