# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.79.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.system_config_template_storage_option_dto import SystemConfigTemplateStorageOptionDto  # noqa: E501

class TestSystemConfigTemplateStorageOptionDto(unittest.TestCase):
    """SystemConfigTemplateStorageOptionDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SystemConfigTemplateStorageOptionDto:
        """Test SystemConfigTemplateStorageOptionDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SystemConfigTemplateStorageOptionDto`
        """
        model = SystemConfigTemplateStorageOptionDto()  # noqa: E501
        if include_optional:
            return SystemConfigTemplateStorageOptionDto(
                day_options = [
                    ''
                    ],
                hour_options = [
                    ''
                    ],
                minute_options = [
                    ''
                    ],
                month_options = [
                    ''
                    ],
                preset_options = [
                    ''
                    ],
                second_options = [
                    ''
                    ],
                year_options = [
                    ''
                    ]
            )
        else:
            return SystemConfigTemplateStorageOptionDto(
                day_options = [
                    ''
                    ],
                hour_options = [
                    ''
                    ],
                minute_options = [
                    ''
                    ],
                month_options = [
                    ''
                    ],
                preset_options = [
                    ''
                    ],
                second_options = [
                    ''
                    ],
                year_options = [
                    ''
                    ],
        )
        """

    def testSystemConfigTemplateStorageOptionDto(self):
        """Test SystemConfigTemplateStorageOptionDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
