# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.79.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.import_asset_dto import ImportAssetDto  # noqa: E501

class TestImportAssetDto(unittest.TestCase):
    """ImportAssetDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImportAssetDto:
        """Test ImportAssetDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImportAssetDto`
        """
        model = ImportAssetDto()  # noqa: E501
        if include_optional:
            return ImportAssetDto(
                asset_path = '',
                device_asset_id = '',
                device_id = '',
                duration = '',
                file_created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                file_modified_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                is_archived = True,
                is_external = True,
                is_favorite = True,
                is_offline = True,
                is_read_only = True,
                is_visible = True,
                library_id = '',
                sidecar_path = ''
            )
        else:
            return ImportAssetDto(
                asset_path = '',
                device_asset_id = '',
                device_id = '',
                file_created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                file_modified_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                is_favorite = True,
        )
        """

    def testImportAssetDto(self):
        """Test ImportAssetDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
