# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.79.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.people_update_dto import PeopleUpdateDto  # noqa: E501

class TestPeopleUpdateDto(unittest.TestCase):
    """PeopleUpdateDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PeopleUpdateDto:
        """Test PeopleUpdateDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PeopleUpdateDto`
        """
        model = PeopleUpdateDto()  # noqa: E501
        if include_optional:
            return PeopleUpdateDto(
                people = [
                    openapi_client.models.people_update_item.PeopleUpdateItem(
                        birth_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        feature_face_asset_id = '', 
                        id = '', 
                        is_hidden = True, 
                        name = '', )
                    ]
            )
        else:
            return PeopleUpdateDto(
                people = [
                    openapi_client.models.people_update_item.PeopleUpdateItem(
                        birth_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        feature_face_asset_id = '', 
                        id = '', 
                        is_hidden = True, 
                        name = '', )
                    ],
        )
        """

    def testPeopleUpdateDto(self):
        """Test PeopleUpdateDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
