# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.79.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.o_auth_api import OAuthApi  # noqa: E501


class TestOAuthApi(unittest.TestCase):
    """OAuthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OAuthApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_authorize_o_auth(self) -> None:
        """Test case for authorize_o_auth

        """
        pass

    def test_callback(self) -> None:
        """Test case for callback

        """
        pass

    def test_generate_config(self) -> None:
        """Test case for generate_config

        """
        pass

    def test_link(self) -> None:
        """Test case for link

        """
        pass

    def test_mobile_redirect(self) -> None:
        """Test case for mobile_redirect

        """
        pass

    def test_unlink(self) -> None:
        """Test case for unlink

        """
        pass


if __name__ == '__main__':
    unittest.main()
