# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.79.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.o_auth_config_response_dto import OAuthConfigResponseDto  # noqa: E501

class TestOAuthConfigResponseDto(unittest.TestCase):
    """OAuthConfigResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OAuthConfigResponseDto:
        """Test OAuthConfigResponseDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OAuthConfigResponseDto`
        """
        model = OAuthConfigResponseDto()  # noqa: E501
        if include_optional:
            return OAuthConfigResponseDto(
                auto_launch = True,
                button_text = '',
                enabled = True,
                password_login_enabled = True,
                url = ''
            )
        else:
            return OAuthConfigResponseDto(
                enabled = True,
                password_login_enabled = True,
        )
        """

    def testOAuthConfigResponseDto(self):
        """Test OAuthConfigResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
