# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.79.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.api_key_api import APIKeyApi  # noqa: E501


class TestAPIKeyApi(unittest.TestCase):
    """APIKeyApi unit test stubs"""

    def setUp(self) -> None:
        self.api = APIKeyApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_create_key(self) -> None:
        """Test case for create_key

        """
        pass

    def test_delete_key(self) -> None:
        """Test case for delete_key

        """
        pass

    def test_get_key(self) -> None:
        """Test case for get_key

        """
        pass

    def test_get_keys(self) -> None:
        """Test case for get_keys

        """
        pass

    def test_update_key(self) -> None:
        """Test case for update_key

        """
        pass


if __name__ == '__main__':
    unittest.main()
