# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.79.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.clip_config import CLIPConfig  # noqa: E501

class TestCLIPConfig(unittest.TestCase):
    """CLIPConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CLIPConfig:
        """Test CLIPConfig
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CLIPConfig`
        """
        model = CLIPConfig()  # noqa: E501
        if include_optional:
            return CLIPConfig(
                enabled = True,
                mode = 'vision',
                model_name = '',
                model_type = 'image-classification'
            )
        else:
            return CLIPConfig(
                enabled = True,
                model_name = '',
        )
        """

    def testCLIPConfig(self):
        """Test CLIPConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
