# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.79.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.shared_link_api import SharedLinkApi  # noqa: E501


class TestSharedLinkApi(unittest.TestCase):
    """SharedLinkApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SharedLinkApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_add_shared_link_assets(self) -> None:
        """Test case for add_shared_link_assets

        """
        pass

    def test_create_shared_link(self) -> None:
        """Test case for create_shared_link

        """
        pass

    def test_get_all_shared_links(self) -> None:
        """Test case for get_all_shared_links

        """
        pass

    def test_get_my_shared_link(self) -> None:
        """Test case for get_my_shared_link

        """
        pass

    def test_get_shared_link_by_id(self) -> None:
        """Test case for get_shared_link_by_id

        """
        pass

    def test_remove_shared_link(self) -> None:
        """Test case for remove_shared_link

        """
        pass

    def test_remove_shared_link_assets(self) -> None:
        """Test case for remove_shared_link_assets

        """
        pass

    def test_update_shared_link(self) -> None:
        """Test case for update_shared_link

        """
        pass


if __name__ == '__main__':
    unittest.main()
