# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.79.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.tone_mapping import ToneMapping  # noqa: E501

class TestToneMapping(unittest.TestCase):
    """ToneMapping unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testToneMapping(self):
        """Test ToneMapping"""
        # inst = ToneMapping()

if __name__ == '__main__':
    unittest.main()
