# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.79.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.server_info_api import ServerInfoApi  # noqa: E501


class TestServerInfoApi(unittest.TestCase):
    """ServerInfoApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ServerInfoApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_get_server_config(self) -> None:
        """Test case for get_server_config

        """
        pass

    def test_get_server_features(self) -> None:
        """Test case for get_server_features

        """
        pass

    def test_get_server_info(self) -> None:
        """Test case for get_server_info

        """
        pass

    def test_get_server_version(self) -> None:
        """Test case for get_server_version

        """
        pass

    def test_get_stats(self) -> None:
        """Test case for get_stats

        """
        pass

    def test_get_supported_media_types(self) -> None:
        """Test case for get_supported_media_types

        """
        pass

    def test_ping_server(self) -> None:
        """Test case for ping_server

        """
        pass


if __name__ == '__main__':
    unittest.main()
