# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.79.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.map_marker_response_dto import MapMarkerResponseDto  # noqa: E501

class TestMapMarkerResponseDto(unittest.TestCase):
    """MapMarkerResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MapMarkerResponseDto:
        """Test MapMarkerResponseDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MapMarkerResponseDto`
        """
        model = MapMarkerResponseDto()  # noqa: E501
        if include_optional:
            return MapMarkerResponseDto(
                id = '',
                lat = 1.337,
                lon = 1.337
            )
        else:
            return MapMarkerResponseDto(
                id = '',
                lat = 1.337,
                lon = 1.337,
        )
        """

    def testMapMarkerResponseDto(self):
        """Test MapMarkerResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
