# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.79.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.job_settings_dto import JobSettingsDto  # noqa: E501

class TestJobSettingsDto(unittest.TestCase):
    """JobSettingsDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JobSettingsDto:
        """Test JobSettingsDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JobSettingsDto`
        """
        model = JobSettingsDto()  # noqa: E501
        if include_optional:
            return JobSettingsDto(
                concurrency = 56
            )
        else:
            return JobSettingsDto(
                concurrency = 56,
        )
        """

    def testJobSettingsDto(self):
        """Test JobSettingsDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
