# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.79.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.server_config_dto import ServerConfigDto  # noqa: E501

class TestServerConfigDto(unittest.TestCase):
    """ServerConfigDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServerConfigDto:
        """Test ServerConfigDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServerConfigDto`
        """
        model = ServerConfigDto()  # noqa: E501
        if include_optional:
            return ServerConfigDto(
                login_page_message = '',
                map_tile_url = '',
                oauth_button_text = ''
            )
        else:
            return ServerConfigDto(
                login_page_message = '',
                map_tile_url = '',
                oauth_button_text = '',
        )
        """

    def testServerConfigDto(self):
        """Test ServerConfigDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
