# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.79.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.system_config_password_login_dto import SystemConfigPasswordLoginDto  # noqa: E501

class TestSystemConfigPasswordLoginDto(unittest.TestCase):
    """SystemConfigPasswordLoginDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SystemConfigPasswordLoginDto:
        """Test SystemConfigPasswordLoginDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SystemConfigPasswordLoginDto`
        """
        model = SystemConfigPasswordLoginDto()  # noqa: E501
        if include_optional:
            return SystemConfigPasswordLoginDto(
                enabled = True
            )
        else:
            return SystemConfigPasswordLoginDto(
                enabled = True,
        )
        """

    def testSystemConfigPasswordLoginDto(self):
        """Test SystemConfigPasswordLoginDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
