# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.79.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.job_api import JobApi  # noqa: E501


class TestJobApi(unittest.TestCase):
    """JobApi unit test stubs"""

    def setUp(self) -> None:
        self.api = JobApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_get_all_jobs_status(self) -> None:
        """Test case for get_all_jobs_status

        """
        pass

    def test_send_job_command(self) -> None:
        """Test case for send_job_command

        """
        pass


if __name__ == '__main__':
    unittest.main()
